name: Check Password Secret

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
    - cron: "0 * * * *"

jobs:
  check-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PASSWORD secret exists
        run: |
          if [ -z "${{ secrets.PASSWORD }}" ]; then
            echo "❌ PASSWORD secret is missing"
            exit 1
          else
            echo "✅ PASSWORD secret exists"
          fi